
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simran
 */
public class Admin_Change_Password extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Change_Password
     */
    String username="";
    public Admin_Change_Password(String username) {
        initComponents();
        this.username=username;
        setSize(600,600);
        setVisible(true);
        j_username.setText(username);
        j_username.setEditable(false);
         
         getContentPane().setBackground(new Color(51,204,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j_username = new javax.swing.JTextField();
        j_old_pass = new javax.swing.JPasswordField();
        j_new_pass = new javax.swing.JPasswordField();
        j_confirm_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 102, 153, 51);

        jLabel2.setText("Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 189, 153, 51);

        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 283, 153, 49);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 376, 153, 45);
        getContentPane().add(j_username);
        j_username.setBounds(363, 102, 178, 51);
        getContentPane().add(j_old_pass);
        j_old_pass.setBounds(363, 194, 178, 41);

        j_new_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_new_passActionPerformed(evt);
            }
        });
        getContentPane().add(j_new_pass);
        j_new_pass.setBounds(363, 285, 178, 45);
        getContentPane().add(j_confirm_pass);
        j_confirm_pass.setBounds(363, 393, 178, 49);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(197, 505, 202, 61);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_new_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_new_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_new_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String oldpass=j_old_pass.getText().toString();
        String newpass=j_new_pass.getText().toString();
        String confirmpass=j_confirm_pass.getText().toString();
        
        if(oldpass.equals("") || newpass.equals("")|| confirmpass.equals(""))
        {
         JOptionPane.showMessageDialog(rootPane, "All fields are required");
        }
        else
        {
         if(newpass.equals(confirmpass))
         {
             try
             {
             HttpResponse<String> httpres=Unirest.get(GlobalClass.ip+"adminchangepass")
                     .queryString("username",username)
                     .queryString("oldpass",oldpass)
                     .queryString("newpass",newpass)
                     .asString();
             if(httpres.getStatus()==200){
                 String res= httpres.getBody();
             JOptionPane.showMessageDialog(rootPane,res);
             Admin_Home obj=new Admin_Home(username);
             }
             }
             catch(Exception e)
                     {
                      e.printStackTrace();
                     }
             
         }
         else
         {
          JOptionPane.showMessageDialog(rootPane,"New Password and Confirm Password should match");
         }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Admin_Change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField j_confirm_pass;
    private javax.swing.JPasswordField j_new_pass;
    private javax.swing.JPasswordField j_old_pass;
    private javax.swing.JTextField j_username;
    // End of variables declaration//GEN-END:variables
}
