/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simran
 */
public class courses_panel extends javax.swing.JPanel {

    /**
     * Creates new form courses_panel
     */
    public courses_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpic = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jdesc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 102));
        setLayout(null);

        jpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jpic);
        jpic.setBounds(23, 16, 141, 129);
        add(jname);
        jname.setBounds(15, 177, 136, 27);
        add(jdesc);
        jdesc.setBounds(15, 222, 149, 36);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jdesc;
    public javax.swing.JLabel jname;
    public javax.swing.JLabel jpic;
    // End of variables declaration//GEN-END:variables
}
