/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simran
 */
public class lectures_pannels extends javax.swing.JPanel {

    /**
     * Creates new form lectures_pannels
     */
    public lectures_pannels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpic = new javax.swing.JLabel();
        jButton_play = new javax.swing.JButton();
        jButton_download = new javax.swing.JButton();
        jtitle = new javax.swing.JLabel();
        jduration = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 102));
        setLayout(null);

        jpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jpic);
        jpic.setBounds(30, 20, 110, 100);

        jButton_play.setText("Play");
        jButton_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_playActionPerformed(evt);
            }
        });
        add(jButton_play);
        jButton_play.setBounds(0, 250, 90, 30);

        jButton_download.setText("Download");
        add(jButton_download);
        jButton_download.setBounds(110, 250, 110, 29);

        jtitle.setText("jLabel1");
        add(jtitle);
        jtitle.setBounds(20, 130, 120, 40);

        jduration.setText("jLabel2");
        add(jduration);
        jduration.setBounds(20, 180, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_playActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_download;
    public javax.swing.JButton jButton_play;
    public javax.swing.JLabel jduration;
    public javax.swing.JLabel jpic;
    public javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
