
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simran
 */
public class User_change_Password extends javax.swing.JFrame {

    /**
     * Creates new form User_change_Password
     */
    String username="";
    public User_change_Password(String username) {
        initComponents();
        this.username=username;
        j_username.setText(username);
        j_username.setEditable(false);
        setSize(600,600);
        setVisible(true);
        getContentPane().setBackground(new Color(51,204,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j_username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        j_oldpassword = new javax.swing.JPasswordField();
        j_newpassword = new javax.swing.JPasswordField();
        j_confirmpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 80, 40);

        jLabel2.setText("Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 130, 40);

        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 130, 50);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 130, 40);
        getContentPane().add(j_username);
        j_username.setBounds(270, 70, 230, 40);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 420, 190, 50);
        getContentPane().add(j_oldpassword);
        j_oldpassword.setBounds(270, 146, 230, 40);
        getContentPane().add(j_newpassword);
        j_newpassword.setBounds(270, 230, 230, 50);
        getContentPane().add(j_confirmpassword);
        j_confirmpassword.setBounds(270, 306, 230, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       // String username=username.getText().toString();   
        String oldpass=j_oldpassword.getText();
        String newpass=j_newpassword.getText();
        String confirmpass=j_confirmpassword.getText();
        
        if(oldpass.equals("") || newpass.equals("")|| confirmpass.equals(""))
        {
         JOptionPane.showMessageDialog(rootPane, "All fields are required");
        }
        else
        {
         if(newpass.equals(confirmpass))
         {
             try
             {
                 System.out.println("old = "+oldpass+"..."+newpass+".");
             HttpResponse<String> httpres=Unirest.get(GlobalClass.ip+"pass")
                     .queryString("username",username)
                     .queryString("oldpass",oldpass)
                     .queryString("newpass",newpass)
                     .asString();
             if(httpres.getStatus()==200){
                 String res= httpres.getBody();
             JOptionPane.showMessageDialog(rootPane,res);
             
            // if(res.equals("success"))
            // {
              ////User_Home obj=new User_Home(username);
            // }
             }
             }
             catch(Exception e)
                     {
                      e.printStackTrace();
                     }
             
         }
         else
         {
          JOptionPane.showMessageDialog(rootPane,"New Password and Confirm Password should match");
         }
        }
        
                                   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new User_change_Password().setVisible(true);
}
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField j_confirmpassword;
    private javax.swing.JPasswordField j_newpassword;
    private javax.swing.JPasswordField j_oldpassword;
    private javax.swing.JTextField j_username;
    // End of variables declaration//GEN-END:variables
}
