
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simran
 */
public class User_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form User_SignUp
     */
    public User_SignUp() {
        initComponents();
        setSize(800,800);
        setVisible(true);
         getContentPane().setBackground(new Color(51,204,255));
        
        jComboBox1.removeAllItems();
        for(int i=0;i<GlobalClass.sec_question.length;i++)
        {
         jComboBox1.addItem(GlobalClass.sec_question[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jconfirmpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jmobileno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jsecurityans = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 127, 43);

        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 109, 37);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 109, 33);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(42, 337, 0, 0);
        getContentPane().add(jusername);
        jusername.setBounds(390, 30, 198, 43);
        getContentPane().add(jemail);
        jemail.setBounds(390, 130, 198, 41);
        getContentPane().add(jpassword);
        jpassword.setBounds(390, 220, 198, 38);

        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 310, 130, 40);
        getContentPane().add(jconfirmpassword);
        jconfirmpassword.setBounds(390, 310, 200, 40);

        jLabel6.setText("Mobile No");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 400, 110, 30);
        getContentPane().add(jmobileno);
        jmobileno.setBounds(390, 390, 200, 40);

        jLabel7.setText("Security Question");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 480, 130, 40);

        jLabel8.setText("Security Answer");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 560, 150, 40);

        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 610, 150, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(390, 470, 200, 40);
        getContentPane().add(jsecurityans);
        jsecurityans.setBounds(390, 550, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String username=jusername.getText();
        String email=jemail.getText();
        String password=jpassword.getText();
        String confirmpass=jconfirmpassword.getText();
        String mobileno=jmobileno.getText();
        String security_ques=jComboBox1.getSelectedItem().toString();
        String security_ans=jsecurityans.getText();
        
         if(username.equals("")|| email.equals("")|| password.equals("") || confirmpass.equals("")|| mobileno.equals(""))
        {
         JOptionPane.showMessageDialog(rootPane, "All fields are required");
        }
        else
             if(password.equals(confirmpass))
        {
            try {
                HttpResponse<String>httpResponse=Unirest.get(GlobalClass.ip+"signup")
                        .queryString("username",username)
                        .queryString("email",email)
                        .queryString("password",password)
                        .queryString("mobileno",mobileno)
                        .queryString("security_ques",security_ques)
                        .queryString("security_ans",security_ans)
                        .asString();
                
                
                
                if(httpResponse.getStatus()==200)
                {
                  String res=httpResponse.getBody();
                  JOptionPane.showMessageDialog(rootPane,res);
                
                }
            } catch (UnirestException ex) {
                Logger.getLogger(User_SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
         
        
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane,"Password and confirm password must match");
        }
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jconfirmpassword;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jmobileno;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jsecurityans;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
